services:

  postgres:
    image: postgres:16
    container_name: rapidlink-postgres
    restart: always
    environment:
      POSTGRES_DB: rapidlink
      POSTGRES_USER: rapidlink_user
      POSTGRES_PASSWORD: rapidlink_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rapidlink-network

volumes:
  postgres_data:

networks:
  rapidlink-network: