-- ============================================================
-- RapidLink - Initial Database Schema (V1)
-- This migration creates the core tables required for
-- URL shortening functionality.
-- ============================================================


-- Extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- Users Table
-- Stores registered users who create and manage short URLs.
-- ============================================================
CREATE TABLE users (
    -- Primary identifier for the user (Auto generated by spring boot)
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Full name of the user (used for display purposes)
        full_name VARCHAR(255) NOT NULL,

    -- User email used for authentication (must be unique)
    email VARCHAR(255) UNIQUE NOT NULL,

    -- Securely hashed password (never store raw passwords)
    password_hash TEXT NOT NULL,

    -- Timestamp when the user account was created
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- Short URLs Table
-- Stores mapping between a generated short code and the
-- original long URL.
-- ============================================================
CREATE TABLE short_urls (
    -- Primary identifier for the short URL (Auto generated by spring boot)
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Unique short code used for shorted link
    -- Example: abc123
    short_code VARCHAR(10) UNIQUE NOT NULL,

    -- The original destination URL
    original_url VARCHAR(2048) NOT NULL,

    -- Optional owner of the link (NULL for anonymous users)
    user_id UUID,

    -- Timestamp when the short URL was created
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Optional expiration time after which the link becomes invalid
    expires_at TIMESTAMP,

    -- Indicates whether the link is active or disabled
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    -- Cached click counter for fast analytics queries
    click_count BIGINT NOT NULL DEFAULT 0,

    -- Foreign key linking the short URL to its owner
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE SET NULL
);

-- ============================================================
-- Performance Indexes (VERY IMPORTANT for scaling)
-- ============================================================

-- Index for faster email lookup (login, auth)
CREATE INDEX idx_users_email ON users(email);

-- Used in redirect API (GET /{shortCode})
CREATE INDEX idx_short_code ON short_urls(short_code);

-- Helps fetch user-specific links (dashboard)
CREATE INDEX idx_short_urls_user_id ON short_urls(user_id);

-- Useful for analytics / sorting (recent links)
CREATE INDEX idx_short_urls_created_at ON short_urls(created_at);

-- If you query active links frequently
CREATE INDEX idx_short_urls_is_active ON short_urls(is_active);